create extension if not exists citext;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 30),
  username_normalized citext not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles drop constraint if exists profiles_display_name_safe_check;
alter table public.profiles add constraint profiles_display_name_safe_check
  check (char_length(display_name) between 2 and 30 and display_name !~ '[[:cntrl:]]');

create table if not exists public.progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.progress drop constraint if exists progress_data_size_check;
alter table public.progress add constraint progress_data_size_check check (
  jsonb_typeof(data) = 'object'
  and octet_length(data::text) <= 524288
  and coalesce(jsonb_typeof(data -> 'sessions'), 'number') = 'number'
  and coalesce((data ->> 'sessions')::numeric, 0) between 0 and 1000000
  and coalesce(jsonb_typeof(data -> 'correct'), 'number') = 'number'
  and coalesce((data ->> 'correct')::numeric, 0) between 0 and 100000000
  and coalesce(jsonb_typeof(data -> 'total'), 'number') = 'number'
  and coalesce((data ->> 'total')::numeric, 0) between 0 and 100000000
  and coalesce(jsonb_typeof(data -> 'history'), 'array') = 'array'
  and coalesce(jsonb_typeof(data -> 'favorites'), 'array') = 'array'
  and coalesce(jsonb_typeof(data -> 'mistakes'), 'array') = 'array'
  and coalesce(jsonb_typeof(data -> 'pendingSimulations'), 'array') = 'array'
);

create table if not exists public.leaderboard (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  average_grade integer not null default 0 check (average_grade between 0 and 100),
  simulation_score_sum integer not null default 0 check (simulation_score_sum >= 0),
  simulation_count integer not null default 0 check (simulation_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.leaderboard add column if not exists average_grade integer not null default 0;
alter table public.leaderboard add column if not exists simulation_score_sum integer not null default 0;
alter table public.leaderboard add column if not exists simulation_count integer not null default 0;

create table if not exists public.simulation_attempts (
  attempt_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  grade integer not null check (grade between 1 and 100),
  created_at timestamptz not null default now(),
  primary key (user_id, attempt_id)
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('communications', 'history', 'psychology', 'softskills', 'algorithms', 'graphics', 'modeling', 'databases', 'security', 'information', 'networks')),
  category text not null default 'technical' check (category in ('technical', 'humanities')),
  audience text not null default 'common' check (audience in ('common', 'it', 'security')),
  difficulty text not null check (difficulty in ('surface', 'understanding', 'application', 'trick')),
  text text not null check (char_length(trim(text)) between 3 and 1000),
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  correct smallint not null check (correct between 0 and 3),
  explanation text not null check (char_length(trim(explanation)) between 3 and 3000),
  source text not null default 'Программа вступительных испытаний 2026',
  code text not null default '' check (char_length(code) <= 10000),
  position integer not null default 0 check (position >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.question_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create index if not exists simulation_attempts_user_created_idx
  on public.simulation_attempts (user_id, created_at desc);
create index if not exists questions_section_position_idx
  on public.questions (section, position, id);

alter table public.profiles enable row level security;
alter table public.progress enable row level security;
alter table public.leaderboard enable row level security;
alter table public.simulation_attempts enable row level security;
alter table public.questions enable row level security;
alter table public.question_favorites enable row level security;

drop policy if exists "profiles readable by authenticated users" on public.profiles;
drop policy if exists "users read own progress" on public.progress;
drop policy if exists "users insert own progress" on public.progress;
drop policy if exists "users update own progress" on public.progress;
drop policy if exists "leaderboard readable by everyone" on public.leaderboard;
drop policy if exists "users update own leaderboard row" on public.leaderboard;
drop policy if exists "authenticated users read questions" on public.questions;
drop policy if exists "admins create questions" on public.questions;
drop policy if exists "admins update questions" on public.questions;
drop policy if exists "admins delete questions" on public.questions;
drop policy if exists "users read own favorites" on public.question_favorites;
drop policy if exists "users add own favorites" on public.question_favorites;
drop policy if exists "users delete own favorites" on public.question_favorites;

create policy "profiles readable by authenticated users" on public.profiles for select to authenticated using (true);
create policy "users read own progress" on public.progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "users insert own progress" on public.progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "users update own progress" on public.progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "leaderboard readable by everyone" on public.leaderboard for select to anon, authenticated using (true);
create policy "authenticated users read questions" on public.questions for select to authenticated using (true);
create policy "admins create questions" on public.questions for insert to authenticated
  with check (exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'));
create policy "admins update questions" on public.questions for update to authenticated
  using (exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'))
  with check (exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'));
create policy "admins delete questions" on public.questions for delete to authenticated
  using (exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'));
create policy "users read own favorites" on public.question_favorites for select to authenticated using ((select auth.uid()) = user_id);
create policy "users add own favorites" on public.question_favorites for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "users delete own favorites" on public.question_favorites for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.questions from public, anon;
grant select, insert, update, delete on table public.questions to authenticated;
grant usage, select on sequence public.questions_id_seq to authenticated;
revoke all on table public.question_favorites from public, anon;
grant select, insert, delete on table public.question_favorites to authenticated;

create or replace function public.record_simulation_result(p_attempt_id bigint, p_grade integer)
returns void
language plpgsql
security definer set search_path = ''
as $$
declare
  inserted_rows integer;
  recent_attempts integer;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if p_attempt_id < 1 or p_grade < 1 or p_grade > 100 then raise exception 'Invalid simulation result'; end if;

  perform pg_advisory_xact_lock(hashtext((select auth.uid())::text));
  if exists (
    select 1 from public.simulation_attempts
    where user_id = (select auth.uid()) and attempt_id = p_attempt_id
  ) then return; end if;
  select count(*) into recent_attempts
  from public.simulation_attempts
  where user_id = (select auth.uid()) and created_at > now() - interval '24 hours';
  if recent_attempts >= 100 then raise exception 'Daily simulation limit exceeded'; end if;

  insert into public.simulation_attempts (attempt_id, user_id, grade)
  values (p_attempt_id, (select auth.uid()), p_grade)
  on conflict do nothing;
  get diagnostics inserted_rows = row_count;

  if inserted_rows = 1 then
    update public.leaderboard
    set simulation_score_sum = simulation_score_sum + p_grade,
        simulation_count = simulation_count + 1,
        average_grade = round((simulation_score_sum + p_grade)::numeric / (simulation_count + 1)),
        updated_at = now()
    where user_id = (select auth.uid());
  end if;
end;
$$;

revoke all on function public.record_simulation_result(bigint, integer) from public, anon;
grant execute on function public.record_simulation_result(bigint, integer) to authenticated;

create or replace function public.get_admin_users()
returns table (
  user_id uuid,
  display_name text,
  email text,
  role text,
  joined_at timestamptz,
  sessions integer,
  accuracy integer,
  favorites integer,
  simulation_count integer,
  average_grade integer
)
language sql
security definer set search_path = ''
as $$
  select
    p.id,
    p.display_name,
    u.email::text,
    p.role,
    p.created_at,
    coalesce((pr.data ->> 'sessions')::integer, 0),
    case when coalesce((pr.data ->> 'total')::integer, 0) > 0
      then round((pr.data ->> 'correct')::numeric / (pr.data ->> 'total')::numeric * 100)::integer
      else 0
    end,
    jsonb_array_length(coalesce(pr.data -> 'favorites', '[]'::jsonb)),
    coalesce(lb.simulation_count, 0),
    coalesce(lb.average_grade, 0)
  from public.profiles p
  join auth.users u on u.id = p.id
  left join public.progress pr on pr.user_id = p.id
  left join public.leaderboard lb on lb.user_id = p.id
  where exists (
    select 1 from public.profiles administrator
    where administrator.id = (select auth.uid()) and administrator.role = 'admin'
  )
  order by p.created_at desc;
$$;

revoke all on function public.get_admin_users() from public;
grant execute on function public.get_admin_users() to authenticated;

create or replace function public.update_display_name(p_display_name text)
returns text
language plpgsql
security definer set search_path = ''
as $$
declare
  clean_name text := trim(p_display_name);
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if char_length(clean_name) < 2 or char_length(clean_name) > 30 then
    raise exception 'Display name must contain from 2 to 30 characters';
  end if;

  update public.profiles
  set display_name = clean_name, username_normalized = lower(clean_name)
  where id = (select auth.uid());
  update public.leaderboard
  set display_name = clean_name, updated_at = now()
  where user_id = (select auth.uid());
  return clean_name;
end;
$$;

revoke all on function public.update_display_name(text) from public;
grant execute on function public.update_display_name(text) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  generated_display_name text;
  generated_username text;
begin
  generated_display_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
    nullif(split_part(new.email, '@', 1), ''),
    'user'
  );
  generated_username := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username_normalized'), ''),
    lower(generated_display_name) || '-' || left(new.id::text, 8)
  );

  insert into public.profiles (id, display_name, username_normalized)
  values (new.id, generated_display_name, generated_username);
  insert into public.progress (user_id) values (new.id);
  insert into public.leaderboard (user_id, display_name) values (new.id, generated_display_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

update public.profiles
set role = 'admin'
where id = (select id from auth.users where lower(email) = 'admin@gmail.com' limit 1);
